---

- hosts: tag_Name_paxos_server
  vars_files:
  - global_vars.yml
  tasks:
  - set_fact:
      my_ip: "\"{{ ansible_host }}:{{ paxos_port }}\""
      ip_list: "\"{{ groups['tag_Name_paxos_server'] | join(':{{ paxos_port }}\",\"') }}:{{ paxos_port }}\""
  - template:
      src: "{{ playbook_dir }}/application.conf.j2"
      dest: "{{ paxos_path }}/application.conf"
      mode: "0600"
  - file:
      path: "{{ paxos_path }}/logs"
      state: directory