language: scala
before_install: pushd paxos

before_deploy:
  sbt "set test in assembly := {}" assembly;
  mkdir deploy-temp;
  cp target/scala-2.12/paxos-iosr.jar deploy-temp/;
  popd;

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "iosr"
  skip_cleanup: true
  upload-dir: travis-builds
  local-dir: deploy-temp/
